set(_CATKIN_CURRENT_PACKAGE "kauil_control")
set(kauil_control_VERSION "0.0.0")
set(kauil_control_MAINTAINER "alejandro <alejandro@todo.todo>")
set(kauil_control_PACKAGE_FORMAT "2")
set(kauil_control_BUILD_DEPENDS "rospy")
set(kauil_control_BUILD_EXPORT_DEPENDS "rospy")
set(kauil_control_BUILDTOOL_DEPENDS "catkin")
set(kauil_control_BUILDTOOL_EXPORT_DEPENDS )
set(kauil_control_EXEC_DEPENDS "rospy")
set(kauil_control_RUN_DEPENDS "rospy")
set(kauil_control_TEST_DEPENDS )
set(kauil_control_DOC_DEPENDS )
set(kauil_control_URL_WEBSITE "")
set(kauil_control_URL_BUGTRACKER "")
set(kauil_control_URL_REPOSITORY "")
set(kauil_control_DEPRECATED "")