set(_CATKIN_CURRENT_PACKAGE "kauil_movement")
set(kauil_movement_VERSION "0.0.0")
set(kauil_movement_MAINTAINER "alejandro <alejandro@todo.todo>")
set(kauil_movement_PACKAGE_FORMAT "2")
set(kauil_movement_BUILD_DEPENDS "rospy")
set(kauil_movement_BUILD_EXPORT_DEPENDS "rospy")
set(kauil_movement_BUILDTOOL_DEPENDS "catkin")
set(kauil_movement_BUILDTOOL_EXPORT_DEPENDS )
set(kauil_movement_EXEC_DEPENDS "rospy")
set(kauil_movement_RUN_DEPENDS "rospy")
set(kauil_movement_TEST_DEPENDS )
set(kauil_movement_DOC_DEPENDS )
set(kauil_movement_URL_WEBSITE "")
set(kauil_movement_URL_BUGTRACKER "")
set(kauil_movement_URL_REPOSITORY "")
set(kauil_movement_DEPRECATED "")