set(_CATKIN_CURRENT_PACKAGE "urg")
set(urg_VERSION "0.0.0")
set(urg_MAINTAINER "alejandro <alejandro@todo.todo>")
set(urg_PACKAGE_FORMAT "2")
set(urg_BUILD_DEPENDS )
set(urg_BUILD_EXPORT_DEPENDS )
set(urg_BUILDTOOL_DEPENDS "catkin")
set(urg_BUILDTOOL_EXPORT_DEPENDS )
set(urg_EXEC_DEPENDS )
set(urg_RUN_DEPENDS )
set(urg_TEST_DEPENDS )
set(urg_DOC_DEPENDS )
set(urg_URL_WEBSITE "")
set(urg_URL_BUGTRACKER "")
set(urg_URL_REPOSITORY "")
set(urg_DEPRECATED "")